/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DateRange: typeof import('./components/DateRange.vue')['default']
    DoasOptions: typeof import('./components/options/DoasOptions.vue')['default']
    EdmOptions: typeof import('./components/options/EdmOptions.vue')['default']
    GpsBaselineOptions: typeof import('./components/options/GpsBaselineOptions.vue')['default']
    GpsCoordinateOptions: typeof import('./components/options/GpsCoordinateOptions.vue')['default']
    LavaDomesOptions: typeof import('./components/options/LavaDomesOptions.vue')['default']
    MagneticOptions: typeof import('./components/options/MagneticOptions.vue')['default']
    PreviewPane: typeof import('./components/PreviewPane.vue')['default']
    RfapDirectionOptions: typeof import('./components/options/RfapDirectionOptions.vue')['default']
    RfapDistanceOptions: typeof import('./components/options/RfapDistanceOptions.vue')['default']
    RfapEnergyOptions: typeof import('./components/options/RfapEnergyOptions.vue')['default']
    RfapTypeOptions: typeof import('./components/options/RfapTypeOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RsamSeismicOptions: typeof import('./components/options/RsamSeismicOptions.vue')['default']
    ScrollWrapper: typeof import('./components/ScrollWrapper.vue')['default']
    SeismicEnergyOptions: typeof import('./components/options/SeismicEnergyOptions.vue')['default']
    SeismicityOptions: typeof import('./components/options/SeismicityOptions.vue')['default']
    SidebarLeftIcon: typeof import('./components/icons/SidebarLeftIcon.vue')['default']
    SidebarRightIcon: typeof import('./components/icons/SidebarRightIcon.vue')['default']
    ThermalOptions: typeof import('./components/options/ThermalOptions.vue')['default']
    TiltmeterOptions: typeof import('./components/options/TiltmeterOptions.vue')['default']
    VogamosEmissionOptions: typeof import('./components/options/VogamosEmissionOptions.vue')['default']
    VogamosTemperatureOptions: typeof import('./components/options/VogamosTemperatureOptions.vue')['default']
    WeatherBabadanOptions: typeof import('./components/options/WeatherBabadanOptions.vue')['default']
    WeatherJurangJeroOptions: typeof import('./components/options/WeatherJurangJeroOptions.vue')['default']
    WeatherPasarbubarOptions: typeof import('./components/options/WeatherPasarbubarOptions.vue')['default']
  }
}
